// <auto-generated />
using System;
using Backend_Riwi_LinkUp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend_Riwi_LinkUp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240913180421_AddingSeeders")]
    partial class AddingSeeders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.Clan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Clans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "berners lee"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ritchie"
                        },
                        new
                        {
                            Id = 3,
                            Name = "gates"
                        },
                        new
                        {
                            Id = 4,
                            Name = "jeff bezzos"
                        });
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.Coder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ClanId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("GenderId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UrlImage")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("GenderId");

                    b.ToTable("Coders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(1992, 5, 22, 1, 17, 51, 0, DateTimeKind.Utc),
                            ClanId = 1,
                            Description = "especialista en front-end",
                            GenderId = 1,
                            Name = "edgar cardona",
                            UrlImage = "https://media.licdn.com/dms/image/v2/D4E03AQH22ztGRhoM2g/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1677008729241?e=1731542400&v=beta&t=89RVHJpVnq8_m5ObsEU3CEs0KVrBraYI4gGWdIEuXEM"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(1988, 9, 30, 1, 17, 51, 0, DateTimeKind.Utc),
                            ClanId = 2,
                            Description = "desarrollador backend",
                            GenderId = 1,
                            Name = "nicolas martinez",
                            UrlImage = "https://avatars.githubusercontent.com/u/164014608?v=4&size=64"
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(1995, 3, 10, 1, 17, 51, 0, DateTimeKind.Utc),
                            ClanId = 2,
                            Description = "desarrolladora de aplicaciones móviles",
                            GenderId = 2,
                            Name = "brayan acosta",
                            UrlImage = "https://media.licdn.com/dms/image/v2/C4D03AQHAwWzaQDI6gw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1641180503207?e=1731542400&v=beta&t=A7lWrZBzJ84ZlLdFsvKA73tbZKdP1vfPGuvf3Ah6XH4"
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateTime(1991, 7, 18, 1, 17, 51, 0, DateTimeKind.Utc),
                            ClanId = 3,
                            Description = "ingeniero devops",
                            GenderId = 1,
                            Name = "jose barreto",
                            UrlImage = "https://media.licdn.com/dms/image/v2/D4E03AQEqn-8BGpvfaw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1724345138906?e=1731542400&v=beta&t=wWL1nKrccb9DfJVg8Dz6v49L3AIpunv8gkovi5BpqgQ"
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateTime(1993, 11, 5, 1, 17, 51, 0, DateTimeKind.Utc),
                            ClanId = 4,
                            Description = "diseñadora ui/ux",
                            GenderId = 2,
                            Name = "juan arias",
                            UrlImage = "https://media.licdn.com/dms/image/v2/D4E03AQGXb8dGisr-wQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1724327950529?e=1731542400&v=beta&t=uCMHF7cJT2SfM-4acPddFycPWzAUYFWYr_WofvG2Cf8"
                        },
                        new
                        {
                            Id = 6,
                            Birthday = new DateTime(1989, 2, 28, 1, 17, 51, 0, DateTimeKind.Utc),
                            ClanId = 1,
                            Description = "científico de datos",
                            GenderId = 1,
                            Name = "juan rojas",
                            UrlImage = "https://media.licdn.com/dms/image/v2/D4E03AQGyhYNRLL9edg/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1681701914743?e=1731542400&v=beta&t=0aYfJifoDREE5dhY4dCSD8IECOotdQqJ5HwtLfAKkxw"
                        },
                        new
                        {
                            Id = 7,
                            Birthday = new DateTime(1994, 6, 12, 1, 17, 51, 0, DateTimeKind.Utc),
                            ClanId = 4,
                            Description = "especialista en seguridad",
                            GenderId = 2,
                            Name = "ava martinez",
                            UrlImage = "https://example.com/ava.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Birthday = new DateTime(1987, 10, 8, 1, 17, 51, 0, DateTimeKind.Utc),
                            ClanId = 1,
                            Description = "desarrollador de videojuegos",
                            GenderId = 1,
                            Name = "noah anderson",
                            UrlImage = "https://example.com/noah.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Birthday = new DateTime(1996, 4, 25, 1, 17, 51, 0, DateTimeKind.Utc),
                            ClanId = 2,
                            Description = "desarrolladora de blockchain",
                            GenderId = 2,
                            Name = "isabella white",
                            UrlImage = "https://example.com/isabella.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Birthday = new DateTime(1990, 1, 15, 1, 17, 51, 0, DateTimeKind.Utc),
                            ClanId = 3,
                            Description = "desarrollador full-stack",
                            GenderId = 1,
                            Name = "alex johnson",
                            UrlImage = "https://example.com/alex.jpg"
                        });
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.CoderLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoderId")
                        .HasColumnType("integer");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("LanguageLevelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoderId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguageLevelId");

                    b.ToTable("CoderLanguages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoderId = 1,
                            LanguageId = 1,
                            LanguageLevelId = 4
                        },
                        new
                        {
                            Id = 2,
                            CoderId = 1,
                            LanguageId = 3,
                            LanguageLevelId = 1
                        },
                        new
                        {
                            Id = 3,
                            CoderId = 2,
                            LanguageId = 1,
                            LanguageLevelId = 3
                        },
                        new
                        {
                            Id = 4,
                            CoderId = 3,
                            LanguageId = 2,
                            LanguageLevelId = 2
                        },
                        new
                        {
                            Id = 5,
                            CoderId = 4,
                            LanguageId = 5,
                            LanguageLevelId = 4
                        },
                        new
                        {
                            Id = 6,
                            CoderId = 5,
                            LanguageId = 3,
                            LanguageLevelId = 5
                        },
                        new
                        {
                            Id = 7,
                            CoderId = 6,
                            LanguageId = 2,
                            LanguageLevelId = 2
                        },
                        new
                        {
                            Id = 8,
                            CoderId = 7,
                            LanguageId = 1,
                            LanguageLevelId = 3
                        },
                        new
                        {
                            Id = 9,
                            CoderId = 8,
                            LanguageId = 5,
                            LanguageLevelId = 4
                        },
                        new
                        {
                            Id = 10,
                            CoderId = 9,
                            LanguageId = 1,
                            LanguageLevelId = 6
                        },
                        new
                        {
                            Id = 11,
                            CoderId = 10,
                            LanguageId = 2,
                            LanguageLevelId = 3
                        });
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.CoderSoftSkill", b =>
                {
                    b.Property<int>("CoderId")
                        .HasColumnType("integer");

                    b.Property<int>("SoftSkillId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("CoderId", "SoftSkillId");

                    b.HasIndex("SoftSkillId");

                    b.ToTable("CoderSoftSkills");

                    b.HasData(
                        new
                        {
                            CoderId = 1,
                            SoftSkillId = 1,
                            Id = 1
                        },
                        new
                        {
                            CoderId = 1,
                            SoftSkillId = 3,
                            Id = 2
                        },
                        new
                        {
                            CoderId = 2,
                            SoftSkillId = 2,
                            Id = 3
                        },
                        new
                        {
                            CoderId = 3,
                            SoftSkillId = 3,
                            Id = 4
                        },
                        new
                        {
                            CoderId = 4,
                            SoftSkillId = 4,
                            Id = 5
                        },
                        new
                        {
                            CoderId = 5,
                            SoftSkillId = 5,
                            Id = 6
                        },
                        new
                        {
                            CoderId = 6,
                            SoftSkillId = 6,
                            Id = 7
                        },
                        new
                        {
                            CoderId = 7,
                            SoftSkillId = 7,
                            Id = 8
                        },
                        new
                        {
                            CoderId = 8,
                            SoftSkillId = 8,
                            Id = 9
                        },
                        new
                        {
                            CoderId = 9,
                            SoftSkillId = 9,
                            Id = 10
                        },
                        new
                        {
                            CoderId = 10,
                            SoftSkillId = 10,
                            Id = 11
                        });
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.CoderTechnicalSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoderId")
                        .HasColumnType("integer");

                    b.Property<int>("TechnicalSkillId")
                        .HasColumnType("integer");

                    b.Property<int>("TechnicalSkillLevelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoderId");

                    b.HasIndex("TechnicalSkillId");

                    b.HasIndex("TechnicalSkillLevelId");

                    b.ToTable("CoderTechnicalSkills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoderId = 1,
                            TechnicalSkillId = 1,
                            TechnicalSkillLevelId = 1
                        },
                        new
                        {
                            Id = 2,
                            CoderId = 1,
                            TechnicalSkillId = 4,
                            TechnicalSkillLevelId = 1
                        },
                        new
                        {
                            Id = 3,
                            CoderId = 2,
                            TechnicalSkillId = 2,
                            TechnicalSkillLevelId = 1
                        },
                        new
                        {
                            Id = 4,
                            CoderId = 3,
                            TechnicalSkillId = 1,
                            TechnicalSkillLevelId = 1
                        },
                        new
                        {
                            Id = 5,
                            CoderId = 4,
                            TechnicalSkillId = 6,
                            TechnicalSkillLevelId = 1
                        },
                        new
                        {
                            Id = 6,
                            CoderId = 5,
                            TechnicalSkillId = 4,
                            TechnicalSkillLevelId = 1
                        },
                        new
                        {
                            Id = 7,
                            CoderId = 6,
                            TechnicalSkillId = 3,
                            TechnicalSkillLevelId = 1
                        },
                        new
                        {
                            Id = 8,
                            CoderId = 7,
                            TechnicalSkillId = 1,
                            TechnicalSkillLevelId = 1
                        },
                        new
                        {
                            Id = 9,
                            CoderId = 8,
                            TechnicalSkillId = 5,
                            TechnicalSkillLevelId = 1
                        },
                        new
                        {
                            Id = 10,
                            CoderId = 9,
                            TechnicalSkillId = 1,
                            TechnicalSkillLevelId = 1
                        },
                        new
                        {
                            Id = 11,
                            CoderId = 10,
                            TechnicalSkillId = 3,
                            TechnicalSkillLevelId = 1
                        });
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "masculino"
                        },
                        new
                        {
                            Id = 2,
                            Name = "femenino"
                        },
                        new
                        {
                            Id = 3,
                            Name = "prefiero no indicarlo"
                        });
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "inglés"
                        },
                        new
                        {
                            Id = 2,
                            Name = "portugues"
                        },
                        new
                        {
                            Id = 3,
                            Name = "francés"
                        },
                        new
                        {
                            Id = 4,
                            Name = "aleman"
                        },
                        new
                        {
                            Id = 5,
                            Name = "chino"
                        });
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.LanguageLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("LanguageLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "a1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "a2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "b1"
                        },
                        new
                        {
                            Id = 4,
                            Name = "b2"
                        },
                        new
                        {
                            Id = 5,
                            Name = "c1"
                        },
                        new
                        {
                            Id = 6,
                            Name = "c2"
                        });
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Sector");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "tecnología"
                        },
                        new
                        {
                            Id = 2,
                            Name = "finanzas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "salud"
                        },
                        new
                        {
                            Id = 4,
                            Name = "educación"
                        },
                        new
                        {
                            Id = 5,
                            Name = "manufactura"
                        });
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.SoftSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("SoftSkills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "comunicación"
                        },
                        new
                        {
                            Id = 2,
                            Name = "trabajo en equipo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "resolución de problemas"
                        },
                        new
                        {
                            Id = 4,
                            Name = "adaptabilidad"
                        },
                        new
                        {
                            Id = 5,
                            Name = "creatividad"
                        },
                        new
                        {
                            Id = 6,
                            Name = "gestión del tiempo"
                        },
                        new
                        {
                            Id = 7,
                            Name = "liderazgo"
                        },
                        new
                        {
                            Id = 8,
                            Name = "inteligencia emocional"
                        },
                        new
                        {
                            Id = 9,
                            Name = "pensamiento crítico"
                        },
                        new
                        {
                            Id = 10,
                            Name = "resolución de conflictos"
                        });
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.TechnicalSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("TechnicalSkills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "javaScript"
                        },
                        new
                        {
                            Id = 2,
                            Name = "python"
                        },
                        new
                        {
                            Id = 3,
                            Name = "java"
                        },
                        new
                        {
                            Id = 4,
                            Name = "c#"
                        },
                        new
                        {
                            Id = 5,
                            Name = "nextJs"
                        },
                        new
                        {
                            Id = 6,
                            Name = "nodeJs"
                        });
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.TechnicalSkillLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TechnicalSkillLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "junior"
                        },
                        new
                        {
                            Id = 2,
                            Name = "semi-senior"
                        },
                        new
                        {
                            Id = 3,
                            Name = "senior"
                        });
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("SectorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("SectorId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 15, 1, 17, 51, 0, DateTimeKind.Utc),
                            Email = "jackeline.cardona@example.com",
                            IsConfirmed = true,
                            Name = "jackeline cardona",
                            PasswordHash = new byte[] { 215, 178, 33, 67, 55, 118, 221, 132, 76, 118, 3, 45, 60, 206, 116, 3, 74, 213, 78, 250, 112, 101, 98, 62, 222, 153, 35, 53, 79, 191, 8, 2, 183, 21, 138, 149, 121, 42, 165, 79, 250, 250, 10, 135, 166, 201, 137, 101, 26, 116, 116, 174, 78, 51, 3, 187, 144, 213, 37, 92, 53, 172, 38, 103 },
                            PasswordSalt = new byte[] { 17, 78, 181, 229, 50, 76, 75, 216, 143, 170, 4, 120, 235, 102, 221, 31, 17, 173, 48, 148, 19, 129, 236, 14, 80, 125, 214, 138, 107, 79, 254, 22, 220, 107, 205, 224, 251, 68, 246, 92, 22, 30, 68, 144, 199, 42, 49, 65, 195, 195, 131, 51, 38, 48, 168, 170, 222, 172, 221, 206, 39, 118, 144, 234, 125, 18, 143, 201, 140, 171, 183, 150, 2, 131, 11, 27, 83, 145, 42, 245, 243, 236, 132, 219, 89, 208, 34, 137, 130, 23, 64, 39, 55, 138, 239, 213, 118, 113, 222, 79, 48, 153, 166, 14, 45, 184, 217, 231, 241, 224, 99, 2, 183, 155, 132, 196, 246, 42, 20, 81, 61, 253, 108, 192, 69, 122, 182, 219 },
                            PhoneNumber = "1234567890",
                            RoleId = 1,
                            SectorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 10, 1, 17, 51, 0, DateTimeKind.Utc),
                            Email = "jane.smith@example.com",
                            IsConfirmed = true,
                            Name = "jane smith",
                            PasswordHash = new byte[] { 246, 49, 139, 134, 0, 30, 196, 175, 123, 27, 76, 22, 238, 192, 88, 173, 230, 39, 49, 65, 245, 120, 138, 125, 92, 178, 2, 225, 184, 185, 46, 66, 174, 11, 85, 191, 109, 41, 215, 4, 189, 185, 85, 178, 209, 210, 136, 83, 174, 158, 229, 2, 160, 176, 60, 145, 251, 215, 221, 205, 123, 27, 170, 94 },
                            PasswordSalt = new byte[] { 235, 83, 208, 204, 179, 238, 99, 248, 193, 199, 91, 8, 25, 215, 246, 169, 196, 0, 58, 247, 56, 94, 208, 134, 58, 245, 223, 166, 241, 251, 99, 19, 255, 217, 6, 146, 125, 110, 122, 235, 130, 236, 219, 6, 88, 6, 194, 159, 191, 85, 82, 223, 27, 82, 9, 107, 6, 179, 227, 35, 209, 161, 74, 165, 212, 20, 54, 2, 140, 74, 176, 61, 19, 143, 204, 112, 167, 48, 129, 83, 107, 181, 11, 105, 50, 248, 98, 12, 231, 34, 179, 58, 229, 103, 252, 173, 172, 227, 233, 246, 27, 229, 2, 124, 152, 155, 204, 7, 215, 52, 254, 83, 43, 224, 221, 59, 91, 112, 171, 74, 105, 191, 134, 218, 241, 185, 234, 112 },
                            PhoneNumber = "2345678901",
                            RoleId = 2,
                            SectorId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 4, 5, 1, 17, 51, 0, DateTimeKind.Utc),
                            Email = "alice.johnson@example.com",
                            IsConfirmed = true,
                            Name = "alice johnson",
                            PasswordHash = new byte[] { 185, 149, 55, 54, 45, 83, 203, 121, 74, 48, 245, 30, 133, 166, 69, 85, 97, 180, 90, 251, 42, 52, 111, 233, 195, 40, 103, 185, 7, 55, 249, 225, 101, 174, 205, 193, 122, 188, 147, 169, 150, 132, 125, 44, 128, 164, 139, 141, 253, 180, 48, 52, 31, 39, 129, 245, 233, 249, 139, 201, 179, 191, 75, 91 },
                            PasswordSalt = new byte[] { 56, 112, 13, 123, 156, 144, 60, 65, 31, 161, 12, 143, 104, 58, 133, 59, 148, 222, 216, 205, 95, 51, 88, 160, 104, 120, 27, 86, 216, 93, 255, 171, 174, 184, 113, 240, 15, 219, 132, 206, 77, 125, 245, 147, 19, 178, 219, 61, 143, 243, 90, 91, 140, 17, 44, 113, 55, 71, 123, 232, 140, 162, 221, 161, 175, 15, 100, 162, 222, 19, 175, 62, 224, 107, 164, 176, 111, 44, 165, 38, 241, 112, 50, 76, 228, 73, 110, 182, 77, 183, 111, 8, 86, 244, 232, 23, 53, 186, 209, 0, 154, 72, 77, 75, 81, 103, 234, 51, 141, 135, 109, 29, 237, 85, 50, 36, 30, 114, 80, 86, 99, 15, 211, 154, 73, 86, 168, 134 },
                            PhoneNumber = "3456789012",
                            RoleId = 2,
                            SectorId = 4
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 5, 20, 1, 17, 51, 0, DateTimeKind.Utc),
                            Email = "bob.williams@example.com",
                            IsConfirmed = true,
                            Name = "bob williams",
                            PasswordHash = new byte[] { 35, 214, 56, 188, 17, 248, 177, 220, 238, 252, 40, 173, 215, 103, 169, 135, 111, 39, 198, 17, 28, 205, 137, 205, 99, 196, 5, 228, 235, 161, 200, 170, 192, 224, 189, 99, 189, 48, 212, 242, 73, 153, 241, 92, 36, 201, 81, 17, 180, 242, 8, 5, 57, 215, 118, 35, 125, 38, 251, 242, 56, 184, 210, 45 },
                            PasswordSalt = new byte[] { 81, 205, 164, 150, 149, 188, 81, 145, 207, 110, 183, 18, 58, 234, 225, 1, 230, 192, 177, 32, 176, 228, 92, 248, 208, 3, 67, 4, 76, 220, 232, 224, 209, 127, 148, 154, 68, 178, 241, 167, 192, 136, 97, 74, 63, 239, 73, 247, 86, 27, 209, 132, 223, 203, 205, 192, 190, 2, 135, 192, 171, 227, 104, 171, 168, 91, 29, 211, 87, 136, 8, 245, 136, 117, 255, 196, 114, 194, 164, 199, 212, 99, 211, 187, 213, 250, 139, 232, 176, 245, 125, 161, 189, 126, 119, 64, 137, 254, 17, 139, 144, 53, 88, 63, 133, 34, 45, 29, 77, 113, 8, 87, 133, 1, 236, 131, 202, 82, 140, 193, 88, 187, 51, 20, 231, 136, 48, 11 },
                            PhoneNumber = "4567890123",
                            RoleId = 2,
                            SectorId = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 5, 25, 1, 17, 51, 0, DateTimeKind.Utc),
                            Email = "charlie.brown@example.com",
                            IsConfirmed = true,
                            Name = "charlie brown",
                            PasswordHash = new byte[] { 110, 70, 176, 166, 66, 1, 110, 147, 219, 26, 102, 13, 231, 196, 73, 45, 91, 247, 84, 99, 201, 51, 9, 84, 20, 91, 230, 233, 72, 194, 219, 182, 236, 136, 175, 188, 69, 56, 52, 25, 207, 228, 84, 54, 252, 79, 105, 122, 62, 186, 67, 180, 122, 52, 209, 83, 31, 5, 184, 113, 132, 208, 248, 192 },
                            PasswordSalt = new byte[] { 149, 119, 95, 107, 142, 74, 159, 130, 161, 11, 237, 129, 39, 214, 39, 167, 169, 249, 4, 74, 88, 64, 223, 213, 74, 255, 218, 128, 245, 107, 145, 133, 229, 171, 102, 94, 70, 202, 42, 93, 112, 31, 59, 255, 223, 176, 192, 179, 231, 161, 140, 174, 197, 13, 167, 231, 60, 146, 251, 98, 28, 174, 95, 114, 36, 71, 250, 232, 235, 19, 21, 38, 221, 73, 0, 42, 179, 132, 95, 180, 82, 190, 51, 205, 8, 133, 228, 43, 143, 185, 177, 153, 132, 146, 42, 82, 37, 225, 215, 207, 233, 237, 137, 190, 167, 51, 224, 19, 142, 174, 95, 13, 203, 177, 246, 227, 61, 251, 40, 173, 35, 225, 105, 161, 191, 209, 43, 92 },
                            PhoneNumber = "5678901234",
                            RoleId = 2,
                            SectorId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 5, 10, 1, 17, 51, 0, DateTimeKind.Utc),
                            Email = "diana.clark@example.com",
                            IsConfirmed = true,
                            Name = "diana clark",
                            PasswordHash = new byte[] { 155, 193, 244, 172, 241, 226, 144, 193, 184, 225, 197, 118, 5, 143, 117, 80, 106, 55, 93, 117, 49, 61, 217, 46, 25, 80, 142, 227, 78, 88, 235, 115, 218, 49, 236, 167, 194, 27, 203, 46, 208, 141, 192, 210, 154, 121, 153, 238, 95, 87, 49, 56, 91, 54, 222, 155, 238, 249, 122, 9, 184, 228, 6, 99 },
                            PasswordSalt = new byte[] { 195, 49, 90, 111, 246, 86, 92, 230, 246, 229, 125, 226, 196, 28, 20, 203, 92, 17, 164, 51, 51, 104, 226, 133, 208, 176, 240, 121, 52, 66, 139, 20, 237, 37, 168, 94, 207, 110, 234, 29, 3, 186, 191, 227, 32, 237, 148, 67, 82, 199, 232, 139, 23, 81, 53, 180, 41, 213, 151, 132, 177, 247, 28, 126, 42, 231, 54, 23, 207, 191, 144, 167, 80, 191, 189, 67, 25, 187, 227, 39, 118, 207, 61, 72, 248, 166, 205, 217, 228, 107, 67, 49, 150, 126, 144, 49, 52, 225, 10, 47, 59, 198, 249, 54, 25, 15, 219, 202, 160, 241, 234, 147, 104, 11, 191, 76, 50, 180, 51, 108, 141, 142, 16, 168, 41, 113, 190, 28 },
                            PhoneNumber = "6789012345",
                            RoleId = 2,
                            SectorId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 6, 15, 1, 17, 51, 0, DateTimeKind.Utc),
                            Email = "edward.davis@example.com",
                            IsConfirmed = true,
                            Name = "edward davis",
                            PasswordHash = new byte[] { 188, 6, 82, 74, 45, 91, 167, 206, 188, 200, 192, 215, 116, 136, 81, 50, 210, 132, 181, 167, 159, 192, 126, 230, 15, 173, 163, 56, 30, 177, 204, 215, 230, 20, 146, 34, 2, 234, 105, 102, 75, 177, 28, 163, 128, 64, 230, 114, 161, 97, 42, 236, 172, 37, 167, 134, 178, 145, 201, 250, 147, 103, 155, 183 },
                            PasswordSalt = new byte[] { 113, 154, 249, 20, 115, 94, 77, 22, 138, 114, 201, 42, 185, 74, 242, 92, 131, 74, 96, 76, 160, 177, 173, 187, 69, 131, 133, 130, 89, 2, 197, 222, 84, 120, 192, 54, 233, 251, 185, 211, 1, 59, 83, 110, 161, 5, 91, 160, 110, 255, 73, 231, 187, 184, 4, 17, 167, 213, 95, 126, 145, 195, 144, 202, 19, 138, 34, 4, 193, 243, 166, 88, 130, 219, 230, 39, 249, 79, 100, 44, 77, 175, 169, 171, 189, 2, 67, 143, 52, 103, 212, 99, 171, 38, 121, 55, 133, 120, 90, 222, 10, 132, 162, 88, 249, 30, 212, 125, 5, 223, 52, 141, 113, 42, 55, 0, 33, 173, 50, 15, 167, 112, 240, 119, 248, 117, 118, 126 },
                            PhoneNumber = "7890123456",
                            RoleId = 2,
                            SectorId = 5
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 7, 10, 1, 17, 51, 0, DateTimeKind.Utc),
                            Email = "fiona.evans@example.com",
                            IsConfirmed = true,
                            Name = "fiona evans",
                            PasswordHash = new byte[] { 86, 112, 109, 82, 15, 228, 105, 212, 209, 208, 121, 153, 169, 114, 33, 116, 205, 194, 249, 231, 188, 9, 58, 171, 189, 63, 175, 49, 20, 70, 21, 168, 19, 169, 223, 65, 106, 75, 215, 38, 13, 255, 166, 150, 84, 70, 228, 214, 125, 199, 79, 248, 37, 76, 132, 112, 159, 249, 65, 98, 68, 9, 84, 102 },
                            PasswordSalt = new byte[] { 136, 76, 12, 231, 153, 62, 67, 186, 240, 162, 23, 22, 155, 223, 122, 93, 193, 51, 159, 254, 2, 100, 125, 28, 158, 199, 118, 247, 39, 36, 21, 23, 183, 234, 29, 116, 97, 99, 232, 149, 111, 126, 199, 251, 172, 159, 237, 0, 169, 148, 87, 120, 58, 21, 146, 59, 99, 24, 89, 79, 110, 126, 210, 199, 88, 218, 56, 136, 248, 148, 81, 61, 33, 170, 133, 200, 140, 35, 39, 187, 254, 86, 170, 39, 252, 73, 233, 131, 74, 121, 80, 134, 187, 78, 41, 233, 48, 89, 132, 72, 33, 123, 193, 112, 112, 168, 34, 12, 207, 12, 79, 233, 168, 149, 136, 169, 116, 5, 189, 228, 186, 135, 234, 120, 89, 221, 204, 35 },
                            PhoneNumber = "8901234567",
                            RoleId = 2,
                            SectorId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 8, 5, 1, 17, 51, 0, DateTimeKind.Utc),
                            Email = "george.fisher@example.com",
                            IsConfirmed = true,
                            Name = "george fisher",
                            PasswordHash = new byte[] { 52, 226, 249, 218, 230, 218, 201, 163, 58, 248, 162, 121, 204, 27, 148, 87, 211, 170, 99, 28, 168, 37, 161, 113, 101, 233, 46, 242, 157, 30, 4, 1, 152, 236, 195, 71, 18, 24, 87, 69, 163, 225, 145, 250, 105, 129, 73, 125, 159, 2, 102, 222, 109, 22, 147, 58, 35, 245, 27, 37, 238, 147, 91, 191 },
                            PasswordSalt = new byte[] { 173, 37, 233, 38, 95, 11, 197, 213, 99, 183, 71, 215, 172, 47, 86, 48, 251, 80, 88, 187, 111, 149, 241, 212, 24, 141, 116, 128, 70, 182, 42, 92, 1, 59, 80, 113, 20, 86, 75, 210, 119, 86, 127, 54, 189, 93, 139, 226, 202, 198, 133, 75, 233, 230, 145, 202, 55, 79, 224, 128, 106, 187, 4, 224, 247, 35, 154, 28, 177, 20, 170, 98, 2, 166, 184, 199, 181, 252, 213, 183, 26, 146, 70, 31, 195, 212, 211, 100, 155, 85, 233, 54, 247, 159, 201, 12, 70, 175, 249, 182, 126, 164, 221, 133, 222, 220, 57, 34, 190, 194, 116, 40, 21, 14, 154, 35, 120, 137, 204, 110, 116, 16, 88, 104, 29, 138, 56, 17 },
                            PhoneNumber = "9012345678",
                            RoleId = 2,
                            SectorId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 9, 1, 1, 17, 51, 0, DateTimeKind.Utc),
                            Email = "hannah.green@example.com",
                            IsConfirmed = true,
                            Name = "hannah green",
                            PasswordHash = new byte[] { 178, 209, 142, 58, 219, 232, 27, 152, 250, 57, 65, 5, 13, 128, 0, 225, 31, 185, 222, 234, 202, 57, 21, 112, 155, 114, 87, 180, 115, 100, 140, 243, 108, 223, 205, 168, 42, 216, 104, 54, 235, 118, 2, 170, 104, 171, 25, 50, 190, 60, 77, 39, 12, 191, 10, 91, 235, 149, 65, 226, 6, 207, 213, 121 },
                            PasswordSalt = new byte[] { 169, 192, 193, 230, 70, 223, 60, 169, 133, 148, 126, 80, 197, 255, 79, 93, 11, 61, 59, 178, 22, 222, 59, 175, 186, 212, 221, 239, 254, 60, 151, 239, 25, 125, 243, 22, 35, 17, 160, 106, 52, 209, 40, 221, 212, 85, 14, 82, 95, 175, 57, 9, 64, 247, 163, 138, 160, 129, 117, 89, 240, 13, 42, 225, 75, 171, 178, 180, 105, 20, 170, 60, 83, 80, 122, 111, 49, 179, 30, 133, 184, 97, 109, 230, 55, 27, 215, 132, 168, 115, 56, 217, 229, 160, 209, 105, 194, 27, 237, 239, 34, 115, 10, 28, 0, 18, 118, 115, 156, 181, 171, 149, 177, 63, 92, 192, 40, 144, 19, 134, 185, 224, 146, 252, 253, 223, 37, 98 },
                            PhoneNumber = "0123456789",
                            RoleId = 2,
                            SectorId = 3
                        });
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "cliente"
                        });
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.Coder", b =>
                {
                    b.HasOne("Backend_Riwi_LinkUp.Models.Clan", "Clan")
                        .WithMany("Coders")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_Riwi_LinkUp.Models.Gender", "Gender")
                        .WithMany("Coders")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.CoderLanguage", b =>
                {
                    b.HasOne("Backend_Riwi_LinkUp.Models.Coder", "Coder")
                        .WithMany("CoderLanguages")
                        .HasForeignKey("CoderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_Riwi_LinkUp.Models.Language", "Language")
                        .WithMany("CoderLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_Riwi_LinkUp.Models.LanguageLevel", "LanguageLevel")
                        .WithMany("CoderLanguages")
                        .HasForeignKey("LanguageLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coder");

                    b.Navigation("Language");

                    b.Navigation("LanguageLevel");
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.CoderSoftSkill", b =>
                {
                    b.HasOne("Backend_Riwi_LinkUp.Models.Coder", "Coder")
                        .WithMany("CoderSoftSkills")
                        .HasForeignKey("CoderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_Riwi_LinkUp.Models.SoftSkill", "SoftSkill")
                        .WithMany("CoderSoftSkills")
                        .HasForeignKey("SoftSkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coder");

                    b.Navigation("SoftSkill");
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.CoderTechnicalSkill", b =>
                {
                    b.HasOne("Backend_Riwi_LinkUp.Models.Coder", "Coder")
                        .WithMany("CoderTechnicalSkills")
                        .HasForeignKey("CoderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_Riwi_LinkUp.Models.TechnicalSkill", "TechnicalSkill")
                        .WithMany("CoderTechnicalSkills")
                        .HasForeignKey("TechnicalSkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend_Riwi_LinkUp.Models.TechnicalSkillLevel", "TechnicalSkillLevel")
                        .WithMany("CoderTechnicalSkills")
                        .HasForeignKey("TechnicalSkillLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coder");

                    b.Navigation("TechnicalSkill");

                    b.Navigation("TechnicalSkillLevel");
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.User", b =>
                {
                    b.HasOne("Backend_Riwi_LinkUp.Models.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_Riwi_LinkUp.Models.Sector", "Sector")
                        .WithMany("Users")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.Clan", b =>
                {
                    b.Navigation("Coders");
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.Coder", b =>
                {
                    b.Navigation("CoderLanguages");

                    b.Navigation("CoderSoftSkills");

                    b.Navigation("CoderTechnicalSkills");
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.Gender", b =>
                {
                    b.Navigation("Coders");
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.Language", b =>
                {
                    b.Navigation("CoderLanguages");
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.LanguageLevel", b =>
                {
                    b.Navigation("CoderLanguages");
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.Sector", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.SoftSkill", b =>
                {
                    b.Navigation("CoderSoftSkills");
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.TechnicalSkill", b =>
                {
                    b.Navigation("CoderTechnicalSkills");
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.TechnicalSkillLevel", b =>
                {
                    b.Navigation("CoderTechnicalSkills");
                });

            modelBuilder.Entity("Backend_Riwi_LinkUp.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
