using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Backend_Riwi_LinkUp.Models;
using Microsoft.EntityFrameworkCore;

namespace Backend_Riwi_LinkUp.Seeders
{
    public class CoderSeeder
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Coder>().HasData(
                new Coder { Id = 1, Name = "edgar cardona", Birthday = new DateTime(1997, 5, 22, 1, 17, 51, DateTimeKind.Utc), Description = "desarrollador de software con experiencia en diseño de soluciones digitales, modelado de datos y metodologías ágiles. me destaco en resolver problemas complejos y en comunicación efectiva.", UrlImage = "https://media.licdn.com/dms/image/v2/D4E03AQH22ztGRhoM2g/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1677008729241?e=1731542400&v=beta&t=89RVHJpVnq8_m5ObsEU3CEs0KVrBraYI4gGWdIEuXEM", ClanId = 1, GenderId = 1 },
                new Coder { Id = 2, Name = "nicolas martinez", Birthday = new DateTime(2006, 9, 30, 1, 17, 51, DateTimeKind.Utc), Description = "desarrollador backend con aptitudes en c#, .net. especializado en aplicaciones del servidor e integración de api. buen trabajo en equipo y solucion de problemas", UrlImage = "https://avatars.githubusercontent.com/u/164014608?v=4", ClanId = 2, GenderId = 1 },
                new Coder { Id = 3, Name = "brayan acosta", Birthday = new DateTime(1995, 3, 10, 1, 17, 51, DateTimeKind.Utc), Description = "actualmente, aprendo y aplico .net, typescript, react, next.js y sql, desarrollando habilidades en aplicaciones web y manejo de bases de datos.", UrlImage = "https://media.licdn.com/dms/image/v2/C4D03AQHAwWzaQDI6gw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1641180503207?e=1731542400&v=beta&t=A7lWrZBzJ84ZlLdFsvKA73tbZKdP1vfPGuvf3Ah6XH4", ClanId = 2, GenderId = 1 },
                new Coder { Id = 4, Name = "jose barreto", Birthday = new DateTime(2003, 7, 18, 1, 17, 51, DateTimeKind.Utc), Description = "apasionado por crear y resolver problemas. me encanta aprender y enfrentar desafíos, compartir conocimientos y desarrollar soluciones innovadoras que impacten positivamente.", UrlImage = "https://media.licdn.com/dms/image/v2/D4E03AQEqn-8BGpvfaw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1724345138906?e=1731542400&v=beta&t=wWL1nKrccb9DfJVg8Dz6v49L3AIpunv8gkovi5BpqgQ", ClanId = 3, GenderId = 1 },
                new Coder { Id = 5, Name = "juan arias", Birthday = new DateTime(2002, 11, 5, 1, 17, 51, DateTimeKind.Utc), Description = "desarrollador frontend con experiencia en react, typescript y next.js, creando aplicaciones web seguras, eficientes y con arquitectura modular.", UrlImage = "https://media.licdn.com/dms/image/v2/D4E03AQGXb8dGisr-wQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1724327950529?e=1731542400&v=beta&t=uCMHF7cJT2SfM-4acPddFycPWzAUYFWYr_WofvG2Cf8", ClanId = 4, GenderId = 1 },
                new Coder { Id = 6, Name = "juan rojas", Birthday = new DateTime(1997, 2, 28, 1, 17, 51, DateTimeKind.Utc), Description = "científico de datos en aprendizaje automático y análisis de datos. experto en python, r y visualización de datos.", UrlImage = "https://media.licdn.com/dms/image/v2/D4E03AQGyhYNRLL9edg/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1681701914743?e=1731542400&v=beta&t=0aYfJifoDREE5dhY4dCSD8IECOotdQqJ5HwtLfAKkxw", ClanId = 1, GenderId = 1 },
                new Coder { Id = 7, Name = "ava martinez", Birthday = new DateTime(1994, 6, 12, 1, 17, 51, DateTimeKind.Utc), Description = "especialista en seguridad informática con experiencia en hacking ético y auditorías de seguridad de sistemas y datos.", UrlImage = "https://tse1.mm.bing.net/th?id=OIG4.KgiAsoOxSdFdiFJvih.W&pid=ImgGn", ClanId = 4, GenderId = 2 },
                new Coder { Id = 8, Name = "noah anderson", Birthday = new DateTime(1987, 10, 8, 1, 17, 51, DateTimeKind.Utc), Description = "desarrollador de videojuegos en unity y unreal engine. especializado en crear experiencias inmersivas y entornos interactivos.", UrlImage = "https://tse3.mm.bing.net/th?id=OIG4.BdR6gNaEahI_dGinSr75&pid=ImgGn", ClanId = 1, GenderId = 2 },
                new Coder { Id = 9, Name = "isabella white", Birthday = new DateTime(1996, 4, 25, 1, 17, 51, DateTimeKind.Utc), Description = "desarrolladora de blockchain con experiencia en ethereum y solidity para contratos inteligentes y aplicaciones descentralizadas.", UrlImage = "https://tse1.mm.bing.net/th?id=OIG4.xpBYsldYYgGJy_7if8T1&pid=ImgGn", ClanId = 2, GenderId = 2 },
                new Coder { Id = 10, Name = "alex johnson", Birthday = new DateTime(1990, 1, 15, 1, 17, 51, DateTimeKind.Utc), Description = "desarrollador full-stack con experiencia en javascript, node.js y frameworks web modernos. experto en desarrollo cliente y servidor.", UrlImage = "https://tse4.mm.bing.net/th?id=OIG3.zDCj3kinyaUjd0kHGTbh&pid=ImgGn", ClanId = 3, GenderId = 1 },
                new Coder { Id = 11, Name = "maria gomez", Birthday = new DateTime(1992, 7, 10, 1, 17, 51, DateTimeKind.Utc), Description = "ingeniera de software con experiencia en java y spring boot. enfocada en construir aplicaciones web escalables y código limpio.", UrlImage = "https://tse4.mm.bing.net/th?id=OIG4..woi4PcXMJrWci3PHx.1&pid=ImgGn", ClanId = 1, GenderId = 2 },
                new Coder { Id = 12, Name = "joseph kim", Birthday = new DateTime(1994, 8, 22, 1, 17, 51, DateTimeKind.Utc), Description = "consultor devops con experiencia en automatización y servicios en la nube. experto en configurar pipelines ci/cd y gestionar infraestructura.", UrlImage = "https://tse2.mm.bing.net/th?id=OIG3.g2nXDL0zV1p0rTcvZOHY&pid=ImgGn", ClanId = 2, GenderId = 1 },
                new Coder { Id = 13, Name = "elena rodriguez", Birthday = new DateTime(1989, 12, 30, 1, 17, 51, DateTimeKind.Utc), Description = "diseñadora de productos con experiencia en investigación de usuarios y prototipado. experta en usabilidad y sistemas de diseño.", UrlImage = "https://tse1.mm.bing.net/th?id=OIG4.cxyneb3Z34jIy_OLnI45&pid=ImgGn", ClanId = 3, GenderId = 1 },
                new Coder { Id = 14, Name = "luis fernandez", Birthday = new DateTime(1995, 11, 3, 1, 17, 51, DateTimeKind.Utc), Description = "desarrollador backend especializado en arquitectura de microservicios y desarrollo de api en java y spring cloud.", UrlImage = "https://tse4.mm.bing.net/th?id=OIG3.qynXeqPsRs8Lov_9_gIi&pid=ImgGn", ClanId = 4, GenderId = 1 },
                new Coder { Id = 15, Name = "natalie o'connor", Birthday = new DateTime(1991, 5, 25, 1, 17, 51, DateTimeKind.Utc), Description = "ingeniera front-end especializada en vue.js y diseño responsivo. experta en crear aplicaciones web dinámicas y accesibles.", UrlImage = "https://tse1.mm.bing.net/th?id=OIG4.wzqtcIUhErA8sGbNbu76&pid=ImgGn", ClanId = 1, GenderId = 2 },
                new Coder { Id = 16, Name = "damian lee", Birthday = new DateTime(1990, 9, 17, 1, 17, 51, DateTimeKind.Utc), Description = "analista de datos con habilidades en sql y herramientas de visualización como tableau. experto en extraer insights para decisiones.", UrlImage = "https://tse1.mm.bing.net/th?id=OIG3.5zeLHiPCO7K2Mh8UZoUG&pid=ImgGn", ClanId = 2, GenderId = 1 },
                new Coder { Id = 17, Name = "zoe wilson", Birthday = new DateTime(1993, 4, 9, 1, 17, 51, DateTimeKind.Utc), Description = "investigadora en inteligencia artificial con foco en procesamiento de lenguaje natural y algoritmos de aprendizaje automático.", UrlImage = "https://tse4.mm.bing.net/th?id=OIG4.dyXC5j5LkJq0TE_mtSMA&pid=ImgGn", ClanId = 3, GenderId = 2 },
                new Coder { Id = 18, Name = "omar harris", Birthday = new DateTime(1988, 11, 18, 1, 17, 51, DateTimeKind.Utc), Description = "administrador de sistemas con experiencia en seguridad de redes y gestión de servidores a gran escala.", UrlImage = "https://tse3.mm.bing.net/th?id=OIG3.cKPpvOrNYcEWjI.dS6vw&pid=ImgGn", ClanId = 4, GenderId = 1 },
                new Coder { Id = 19, Name = "julia patel", Birthday = new DateTime(1996, 6, 21, 1, 17, 51, DateTimeKind.Utc), Description = "desarrolladora web especializada en front-end y diseño ux. experta en crear sitios web dinámicos y mejorar la experiencia del usuario.", UrlImage = "https://tse2.mm.bing.net/th?id=OIG4.co0F_z3mYCkQ.RjY69sX&pid=ImgGn", ClanId = 1, GenderId = 2 },
                new Coder { Id = 20, Name = "antonio martinez", Birthday = new DateTime(1992, 12, 2, 1, 17, 51, DateTimeKind.Utc), Description = "ingeniero en la nube con experiencia en aws y azure. experto en diseñar soluciones y optimizar infraestructura en la nube.", UrlImage = "https://tse3.mm.bing.net/th?id=OIG3.YXT9SEBhS2aviUM5zMrC&pid=ImgGn", ClanId = 2, GenderId = 1 }

            );
        }
    }
}