name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Backend_Riwi_LinkUp/Backend_Riwi_LinkUp.csproj

    - name: Build
      run: dotnet build Backend_Riwi_LinkUp/Backend_Riwi_LinkUp.csproj --configuration Release

    - name: Publish
      run: dotnet publish Backend_Riwi_LinkUp/Backend_Riwi_LinkUp.csproj --configuration Release --output ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tu-app-service-name'  # Reemplaza con el nombre de tu App Service en Azure
        slot-name: 'Production'
        #publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './publish'
