name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Build and push Docker image
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway link --environment production --project Linkup_ms
          railway up --service Backend_Riwi_LinkUp
          docker build -t backend_riwi_linkup .
          railway run --service Backend_Riwi_LinkUp -- docker push railway.app/backend_riwi_linkup

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service Backend_Riwi_LinkUp