name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Build and push Docker image
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE_NAME: ${{ secrets.RAILWAY_SERVICE_NAME }}
        run: |
          railway link --project $RAILWAY_PROJECT_ID --environment ${{ secrets.RAILWAY_ENVIRONMENT_NAME }}
          railway up --service $RAILWAY_SERVICE_NAME
          docker build -t $RAILWAY_SERVICE_NAME .
          railway run --service $RAILWAY_SERVICE_NAME -- docker push railway.app/$RAILWAY_SERVICE_NAME

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE_NAME: ${{ secrets.RAILWAY_SERVICE_NAME }}
        run: railway up --service $RAILWAY_SERVICE_NAME